title_name = "DEAD OR ALIVE 4"
title_id = "544307D1" # TC-2001
hash = "7F840B8DEFDB5C5E" # default.xex
#media_id = "2AD7FA3A"

[[patch]]
    name = "255-hit Combo Limit"
    desc = "Increases the combo limit from 30 to 255"
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.be8]]
        address = 0x82502197
        value = 0xff

[[patch]]
    name = "Increased Max Character Distance"
    desc = "Increases the maximum distance between characters from 6.0f to 420.0f"
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.be32]]
        address = 0x822a9df8
        value = 0x43d20000

[[patch]]
    name = "Alpha-152 can now be selected!"
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.array]] #replace random-select with alpha-152 and appropriate icons and banners
        address = 0x82f4b960
        value = "1001010100060018000600180006003200060032000600b9000600b9000600610006004900000000"
    [[patch.be8]] #restore 24th slot
        address = 0x821b52d3
        value = 0x01
    [[patch.be32]] #place random-select on slot 24 and enable
        address 0x82f4b988
        value = 0xff010101

[[patch]]
    name = "All Characters Unlocked"
    desc = "Multiplayer Modes Only. Story Mode Unaffected."
    author = "ryu_highabusa"
    is_enabled = false

    [[patch.be8]] #unlock Helena
        address = 0x82f4b872
        value = 0x01
    [[patch.be8]] #unlock Ein
        address = 0x82f4b89a
        value = 0x01
    [[patch.be8]] #unlock Genfu
        address = 0x82f4b8c2
        value = 0x01
    [[patch.be8]] #unlock Leon
        address = 0x82f4b8ea
        value = 0x01
    [[patch.be8]] #unlock Tengu
        address = 0x82f4b912
        value = 0x01
    [[patch.be8]] #unlock Spartan-458
        address = 0x82f4b93a
        value = 0x01

[[patch]]
    name = "Restore Extra Character Slot + Random"
    desc = "(Not sure if Alpha-152 appears in random)"
    author = "ryu_highabusa"
    is_enabled = false


